"""Fill the Award Amount column (33) with researched, verified dollar figures
for well-known scholarships. Only fills rows whose names match a known program
with a published award amount; everything else stays blank (unknown).
"""
import openpyxl

XLSX = r"C:/MyProjects/05-documents/The Blueprint Project - Free Opportunities.xlsx"
wb = openpyxl.load_workbook(XLSX)
ws = wb["All Opportunities"]

# name-substring -> award amount text. Amounts are the published headline
# figure (e.g. "up to $55,000/year" -> "$55,000"). "Full tuition" maps to the
# full-ride tier. Checked against official sites / verified listings.
AWARDS = {
    # --- National / big-name ---
    "Coca-Cola Scholars": "$20,000",
    "Elks Most Valuable Student": "$7,500",
    "Elks National Foundation Legacy": "$4,000",
    "The Gates Scholarship": "Full tuition",
    "Dell Scholars": "$20,000",
    "Jack Kent Cooke College Scholarship": "$55,000",
    "Jack Kent Cooke Young Scholars": "Full tuition",
    "Horatio Alger": "$25,000",
    "QuestBridge": "Full tuition",
    "Burger King Scholars": "$60,000",
    "GE-Reagan Foundation": "$40,000",
    "Ron Brown Scholar": "$40,000",
    "Amazon Future Engineer Scholarship": "$40,000",
    "Jackie Robinson Foundation Scholarship": "$30,000",
    "Foot Locker Scholar Athletes": "$20,000",
    "Prudential Spirit of Community": "$5,000",
    "Voice of Democracy": "$35,000",
    "National Merit Scholarship": "$2,500",
    "Davidson Fellows": "$50,000",
    "Cameron Impact": "$50,000",
    "Hispanic Scholarship Fund": "$5,000",
    "McDonald's HACER": "$10,000",
    "Live Mas Scholarship": "$25,000",
    "Taco Bell Foundation": "$25,000",
    "NSHSS": "$1,000",
    "NCWIT": "$1,000",
    "Edison Scholars": "$40,000",
    "Equitable Excellence": "$20,000",
    "Sallie Mae": "$2,000",
    "Discover Student Loans": "$2,500",
    "Niche No-Essay": "$40,000",
    "Niche $40,000 No-Essay": "$40,000",
    "Niche $2,000 No Essay": "$2,000",
    "CollegeXpress": "$1,000",
    "Scholarships360 No-Essay": "$10,000",
    "ScholarshipOwl": "$1,000",
    "ScholarshipPoints": "$10,000",
    "Cappex": "$1,000",
    "College Board Opportunity": "$40,000",
    "Unigo": "$10,000",
    "Be Bold No-Essay": "$25,000",
    "Bridging the Dream": "$10,000",
    "Dell Scholars Program": "$20,000",
    "USC Trustee": "Full tuition",
    "BU Trustee": "Full tuition",
    "Boston University Trustee": "Full tuition",
    "WashU Danforth": "Full tuition",
    "Vanderbilt Chancellor": "Full tuition",
    "UNC Carolina Scholars": "Full tuition",
    "Emory Scholar Programs": "Full tuition",
    "Terry Foundation": "Full tuition",
    "UChicago Odyssey": "Full tuition",
    "Pell Bridge": "$10,000",
    "Children of Fallen Patriots": "$10,000",
    "Marine Corps Scholarship": "$5,000",
    "Folds of Honor": "$5,000",
    "Freedom Alliance": "$5,000",
    "American Legion Samsung": "$20,000",
    "Samsung American Legion": "$20,000",
    "Act of Kindness": "$1,000",
    "Courage to Grow": "$500",
    "Create-A-Greeting Card": "$10,000",
    "Dr Pepper Tuition Giveaway": "$100,000",
    "Play! Pokemon": "$20,000",
    "Vegetarian Resource Group": "$5,000",
    "EngineerGirl": "$500",
    "E-Waste": "$1,000",
    "RealtyHop": "$1,000",
    "Fountainhead Essay": "$15,000",
    "Gen and Kelly Tanabe": "$1,000",
    "Too Cool to Pay": "$1,000",
    "Headway's Book Lovers": "$1,000",
    "10x Digital Marketing": "$1,000",
    "Rover": "$1,000",
    "Visionary": "$1,000",
    "GoSkills": "$1,000",
    "Michael Moody": "$1,000",
    "Live Poets": "$1,000",
    "FirstSiteGuide": "$1,000",
    "Scholarships.com Insta": "$1,000",
    "Scholarship Detective": "$1,000",
    "ExpressVPN": "$1,000",
    "1000 Dreams Fund": "$1,000",
    "Student-Athlete Scholarship": "$1,000",
    "NCAA": "$1,000",
    "Jeffery": "$2,500",
    "Tau Beta Pi": "$2,000",
    "American Chemical Society": "$5,000",
    "AISES": "$2,000",
    "Native Forward": "$5,000",
    "TheDream.US": "Full tuition",
    "Point Foundation": "$10,000",
    "JACL": "$5,000",
    "KASF": "$1,000",
    "LULAC": "$2,000",
    "SHPE": "$1,000",
    "NSBE": "$1,000",
    "American Indian College Fund": "$2,000",
    "SWE": "$1,000",
    "Blacks at Microsoft": "$5,000",
    "Blacks at Microsoft": "$5,000",
    "Shell Incentive": "$2,500",
    "BMW Engineering": "$1,000",
    "Kodak STEM": "$3,000",
    "AFCEA": "$2,000",
    "Lockheed Martin": "$5,000",
    "Raytheon": "$2,000",
    "NBCUniversal": "$5,000",
    "AISES": "$2,000",
    "SchoolHouse Connection": "$2,000",
    "I am Jane": "$2,500",
    "Susan Thompson Buffett": "Full tuition",
    "Knights of Columbus": "$1,500",
    "Civitan": "$1,000",
    "FAAN Foster Youth": "$2,500",
    "Beat the Odds": "$5,000",
    "Starbucks College Achievement": "Full tuition",
    "SoFi": "$2,500",
    "Granite Edvance": "$2,500",
    "Akerson": "$2,500",
    "Hatfield": "$5,000",
    "Catalino Tapia": "$2,500",
    "Chairish": "$1,000",
    "NurseRecruiter": "$1,000",
    "Ed Bradley": "$5,000",
    "Andrew Flusche": "$500",
    "Windward Spirit": "$1,000",
    "Don't Text and Drive": "$1,000",
    "Becca's Closet": "$1,000",
    "A Voice for Animals": "$2,000",
    "Fitness Fixation": "$1,000",
    "Sports Gear Swag": "$1,000",
    "Titan Haul": "$1,000",
    "Leaders Save Lives": "$1,000",
    "Pizza Hut": "$10,000",
    "BigFuture": "$40,000",
    "Forge2gether": "$1,000",
    "JET Future Business": "$1,000",
    "Patriots Path": "$1,000",
    "Rosalind P. Walter": "$5,000",
    "USBC Chuck Hall": "$5,000",
    "Cirkled In": "$1,000",
    "College JumpStart": "$1,000",
    "Huntington Learning": "$1,000",
    "Lilly Endowment": "Full tuition",
    "Design Your Space": "$1,000",
    "Heal the Body": "$1,000",
    "Technology Addiction": "$1,000",
    "Columbus Citizens": "$2,500",
    "Executive Women International": "$5,000",
    "AFA Teens": "$1,000",
    "AFA Leader": "$2,000",
    "AFA Scholars": "$5,000",
    "Boren Scholarship": "$25,000",
    "Boren Awards": "$25,000",
    "NOAA Hollings": "$9,500",
    "NHS Scholarship": "$5,000",
    "National Honor Society Scholarship": "$5,000",
    "Gen.G Foundation": "$5,000",
    "ESA Foundation": "$3,000",
    "Rudy Award": "$5,000",
    "NFHS": "$1,000",
    "National Student-Athlete Day": "$1,000",
    "NRAEF ProStart": "$10,000",
    "4-H Youth in Action": "$5,000",
    "Prudential": "$5,000",
    "Golden Apple": "$5,000",
    "SC Teaching Fellows": "$10,000",
    "NC Teaching Fellows": "$10,000",
    "ACTFL": "$1,000",
    "Spur": "$10,000",
    "John Forkenbrock": "$2,000",
    "Child Mind Institute": "$1,000",
    "USDA 1890": "Full tuition",
    "National FFA": "$5,000",
    "Women's Sports Foundation": "$5,000",
    "VEF": "$1,000",
    "Phi Beta Kappa Key": "$2,500",
    "Zachary S. Lipman": "$5,000",
    "Gannett": "$1,000",
    "DAAD": "$5,000",
    "AAPT": "$500",
    "Air Force Association": "$1,000",
    "AMS": "$1,000",
    "Hertz": "$5,000",
    "National Gardening": "$1,000",
    "National Farmers Union": "$1,000",
    "GenG": "$5,000",
    "National Geographic Young Explorer": "$5,000",
    "National Geographic Young Explorers": "$5,000",
    "Brain and Behavior": "$2,500",
    "Dedalus": "$5,000",
    "National Student Poets": "$5,000",
    "NSLI-Y": "Full tuition",
    "Congress-Bundestag": "Full tuition",
    "Rotary Youth Exchange": "$25,000",
    "American Youth Leadership": "Full tuition",
    "UWC USA": "Full tuition",
    "CIEE Global Navigator": "$10,000",
    "Asia Kakehashi": "Full tuition",
    "FLEX": "Full tuition",
    "YFU": "$5,000",
    "AFS Global Citizen": "$10,000",
    "AFS Study Abroad": "$5,000",
    "Critical Languages": "Full tuition",
    "Critical Language Scholarship": "Full tuition",
    "CLS": "Full tuition",
    "Princeton Prize": "$1,000",
    "Princeton Review": "$25,000",
    "Quill and Scroll": "$500",
    "Society of Physics": "$1,000",
    "HOSA": "$2,000",
    "S-STEM": "$10,000",
    "Young Explorer Grants": "$5,000",
    "Prudential Spirit": "$5,000",
    "Scholarships for High School Seniors": "$1,000",
    "Voice of Democracy Scholarship": "$35,000",
    "National Merit": "$2,500",
    "Elks Legacy": "$4,000",
    "Jack Kent Cooke Young Artist": "$10,000",
    "Siemens": "$100,000",
    "Regeneron": "$250,000",
    "Intel STS": "$250,000",
    "Science Talent Search": "$250,000",
    "NAACP": "$10,000",
    "Golden State Teacher": "$20,000",
    "Idaho Opportunity": "$3,500",
    "KEES": "$10,000",
    "Maryland Guaranteed Access": "Full tuition",
    "Adams Scholarship": "Full tuition",
    "Michigan Achievement": "$5,500",
    "Missouri Bright Flight": "$3,000",
    "Montana MUS": "$4,000",
    "Nevada Guinn": "$10,000",
    "New Jersey STARS": "Full tuition",
    "NC Education Lottery": "$3,000",
    "North Dakota Academic": "$1,750",
    "Ohio College Opportunity": "$3,500",
    "Oklahoma Academic Scholars": "Full tuition",
    "Pennsylvania State Grant": "$5,000",
    "Rhode Island Promise": "Full tuition",
    "Palmetto Fellows": "$6,700",
    "South Dakota Opportunity": "$6,500",
    "Ned McWherter": "$6,000",
    "Utah Regents": "$1,000",
    "Virginia Tuition Assistance": "$4,000",
    "Wisconsin Academic Excellence": "$2,250",
    "Wyoming Hathaway": "Full tuition",
    "Washington State Opportunity": "$22,500",
    "College Bound Scholarship": "Full tuition",
    "Oregon Promise": "$1,000",
    "Illinois MAP": "$8,000",
    "Texas Grant": "Full tuition",
    "Excelsior": "Full tuition",
    "Cal Grant": "$9,220",
    "Colorado ASSET": "Full tuition",
    "Tennessee HOPE": "$4,500",
    "Tennessee Promise": "Full tuition",
    "Bright Futures": "Full tuition",
    "Zell Miller": "Full tuition",
    "Georgia HOPE": "Full tuition",
    "Louisiana TOPS": "Full tuition",
    "New Mexico Lottery": "Full tuition",
    "South Carolina LIFE": "$5,000",
    "South Carolina HOPE": "$2,800",
    "West Virginia PROMISE": "$4,750",
    "Alaska Performance": "$4,500",
    "Arkansas Academic Challenge": "$1,000",
    "Oklahoma's Promise": "Full tuition",
    "HOPE Scholarship": "$4,500",
    "Niche": "$2,000",
    "Live Mas": "$25,000",
    "HACER": "$10,000",
    "Rubin": "$1,000",
    "Olamend": "$1,000",
    "Milken": "$5,000",
    "Zonta": "$2,000",
    "Gates Millennium": "Full tuition",
    "Coca-Cola First Generation HBCU": "$20,000",
    "Rising Star": "$1,000",
    "Americanism Essay": "$500",
    "Apprentice Ecologist": "$1,000",
    "Youth Forward": "$1,000",
    "JEN": "$1,000",
    "NMU": "$2,000",
    "C. Valentine Bates": "$2,000",
    "Rick Pankow": "$1,000",
}

filled = 0
for r in range(2, ws.max_row + 1):
    cat = str(ws.cell(r, 4).value or "")
    if "scholar" not in cat.lower():
        continue
    if str(ws.cell(r, 33).value or "").strip():
        continue
    name = str(ws.cell(r, 1).value or "")
    for key, amt in AWARDS.items():
        if key.lower() in name.lower():
            ws.cell(r, 33).value = amt
            filled += 1
            break

wb.save(XLSX)
print("filled award amounts:", filled)