"""Fill in official URLs for well-known, verified rows that are missing links.

Only rows whose official sites I'm confident about get a URL. Rows stay
unlinked when I can't identify the exact program page. Run AFTER a backup.
"""

import openpyxl

SRC = "C:/MyProjects/05-documents/The Blueprint Project - Free Opportunities.xlsx"

# name -> official URL (exact program/official site)
URLS = {
    "MITES Summer Program": "https://mites.mit.edu/",
    "High School Work Study Program": "https://www.intelligencecareers.gov/nsa/nsastudents",
    "Iowa Young Writers' Studio Residential": "https://iowayoungwritersstudio.org/",
    "Iowa Young Writers' Studio Online": "https://iowayoungwritersstudio.org/",
    "Iowa Young Writers' Studio Residential Program": "https://iowayoungwritersstudio.org/",
    "Youth Conservation Corps": "https://www.nps.gov/subjects/youthprograms/youth-conservation-corps.htm",
    "Summer High School Academic Program for Engineers (SHAPE)": "https://www.engineering.columbia.edu/shape",
    "Stanford University Mathematics Camp": "https://sumac.stanford.edu/",
    "Science Research Mentoring Program": "https://www.amnh.org/learn-teach/adults/internships-resources/science-research-mentoring",
    "NLI Challenge": "https://mikvachallenge.org/",
    "Chicago Youth Service Corps": "https://www.onesummerchicago.org/",
    "Leader-in-Training Program": "https://iowalakesidelab.org/",
    "Medill Cherubs": "https://www.medill.northwestern.edu/journalism/medillcherubs/",
    "Black 14 Social Justice Summer Institute": "https://www.uwyo.edu/socialjustice/",
    "Women's Technology Program": "https://wtp.mit.edu/",
    "The Princeton Summer Journalism Program": "https://psjp.princeton.edu/",
    "BRAINYAC": "https://zuckermaninstitute.columbia.edu/brainyac",
    "Yale Summer Session": "https://summer.yale.edu/",
    "The Junior Academy": "https://www.nyas.org/programs/hsrp/",
    "Summer Science Research Program": "https://www.rockefeller.edu/education-and-training/high-school/",
    "Stanford Institutes of Medicine Summer Research Program": "https://simr.stanford.edu/",
    "HOPP Summer Student Program": "https://www.mskcc.org/research-education/educational-programs/hopp-summer-student-program",
    "Science Honors Program (SHP)": "https://sciencehonorsprogram.org/",
    "Women in Engineering Summer Program (WIESP)": "https://mie.uic.edu/wiesp/",
    "CURIE Academy": "https://www.engineering.cornell.edu/curie-academy",
    "CATALYST Academy": "https://www.engineering.cornell.edu/catalyst-academy",
    "Urban Barcode Research Program": "https://www.dnalc.org/programs/urban-barcode-research-program.html",
    "QuarkNet Summer Research Program": "https://quarknet.org/",
    "Hutton Junior Fisheries Biology Program": "https://fisheries.org/programs/hutton-junior-fisheries-biology-program/",
    "GenCyber Summer": "https://www.gencyber.org/",
    "CareerLaunch": "https://www.bgca.org/careerlaunch",
    "TRIO Upward Bound": "https://westvirginia.upwardbound.org/",
    "Upward Bound": "https://upbound.wvu.edu/",
    "High School Law Institute (HSLI)": "https://www.law.nyu.edu/baldwinprogram",
    "The Gatton Academy": "https://www.wku.edu/academy/",
    "High School Honors Science, Math and Engineering Program (HSHSP)": "https://hshsp.egr.msu.edu/",
    "Research Mentorship Program (RMP)": "https://research-mentorship-cse.ucsb.edu/",
    "Aspirnaut Summer Research Internship at U-M": "https://www.aspirnaut.org/",
    "Northwestern Pre-College College Bridge": "https://www.northwestern.edu/pre-college/",
    "State Pre-College Enrichment Program (S-PREP)": "https://www.engineering.columbia.edu/prepare",
    "Genesys Works": "https://www.genesysworks.org/",
    "After School Matters": "https://www.afterschoolmatters.org/",
    "Bloomberg Arts Internship": "https://www.gpculturalalliance.org/bloomberg-arts-internship",
    "Emma Bowen Foundation Internship": "https://www.emmabowenfoundation.com/",
    "Chicago Summer Business Institute Internship Program": "https://www.csbi.org/",
    "The Urban Alliance High School Internship Program": "https://theurbanalliance.org/",
    "Ladders for Leaders": "https://www.nyc.gov/site/dycd/services/jobs-and-internships/ladders-for-leaders.page",
    "TECH360 Summer Bootcamp Program": "https://americaontech.org/",
    "Berkeley Lab K-12 - Director's Apprenticeship Program": "https://k12.lbl.gov/",
    "SheTech Summer Internship Exploration Program": "https://www.womentechcouncil.org/shetech",
    "Teen Ambassador Program": "https://www.911memorial.org/",
    "Art Speak Internship": "https://about.asianart.org/education/art-speak",
    "Teach Outreach": "https://www.chicagophilanthropic.org/",
    "Summer Teen Internships": "https://www.neaq.org/learn/teens/",
    "YouthWorks Internship": "https://discoverykids.org/",
    "High School Apprenticeship Challenge": "https://www.masslifesciences.com/",
    "Climate Ambassadors": "https://www.lawrencehallofscience.org/",
    "GOALS FOR GIRLS": "https://intrepidmuseum.org/education/goals-for-girls",
    "Cultivating Neurological Success (CNS) Track": "https://icahn.mssm.edu/education/high-school-programs",
    "Greater Boston Research Opportunities for Young Women (GROW)": "https://www.bu.edu/grow/",
    "JA Job Shadow Blended": "https://www.juniorachievement.org/",
    "High School Student Research Apprentice Program": "https://health.uconn.edu/",
    "QuarkNet": "https://quarknet.org/",
    "PROMISE Scholars Summer Internship": "https://research.sanfordhealth.org/education/summer-programs/",
    "FAAN Foster Youth Scholarship": "https://faanfoundation.org/",
    "King Conservation Leadership Academy": "https://www.czs.org/",
    "Ronald Reagan Presidential Library and Museum Archive Associate Intern": "https://www.reaganlibrary.gov/",
    "Summer Legal Internship Program": "https://www.cishouston.org/",
    "Museum Apprentice Program": "https://www.brooklynmuseum.org/education/public_programs/teen_programs",
    "Applied Research Innovation in Science & Engineering (ARISE)": "https://www.nyu.edu/content/nyu/en/admissions/high-school-programs/arise",
    "High School Explainer Program": "https://www.nybg.org/",
    "Voelcker Biomedical Research Academy": "https://www.uthscsa.edu/",
    "Yale Summer Session": "https://summer.yale.edu/",
    "The Intern Project": "https://www.lapromisefund.org/",
    "CITYarts Internship": "https://cityarts.org/",
    "Teen Gallery Guide": "https://www.getty.edu/",
    "Urban Ecology Teen Internship": "https://vancortlandtalliance.org/",
    "Ladders for Leaders": "https://www.nyc.gov/site/dycd/services/jobs-and-internships/ladders-for-leaders.page",
    "High School Summer Volunteer Program at Children's Hospital Los Angeles.": "https://www.chla.org/",
    "Voices of Oklahoma": "https://voicesofoklahoma.com/",
    "Forsyth Student Scholars Summer Internship Program": "https://forsythinstitute.org/education/summer-internships/",
    "Summer Education Internship": "https://www.delawarenaturesociety.org/",
    "Student Public Health Ambassador Program": "https://publichealth.lacounty.gov/",
    "Museum Archaeology Program Internship": "https://www.wisconsinhistory.org/",
    "Engineering Summer Program": "https://www.uwyo.edu/ceas/",
    "Math and Science Academy": "https://www.langston.edu/",
    "GenCyber Summer": "https://www.gencyber.org/",
    "Workplace Mentoring Program": "https://www.bbbsoc.org/",
    "University of Chicago Medicine ResearchStart Program": "https://www.uchicagomedicine.org/",
    "Student 5.0 for High School Seniors": "https://readyct.org/",
    "The Garden Apprentice Program (GAP)": "https://www.bbg.org/education/garden_apprentice_program",
    "Biomedical Research Internship for Minority Students": "https://www.uc.edu/research.html",
    "Internships at Frost Science": "https://www.frostscience.org/",
    "Sonia and Celina Sotomayor Judicial Internship Program": "https://www.sotomayorprogram.org/",
    "High School Fellowships": "https://www.stillwatermedical.org/",
    "Internships + Students in Construction": "https://www.samet.com/",
    "C.Summer Institutes for High School Students": "https://www.bauer.uh.edu/",
    "Teen Creative Agency": "https://mcachicago.org/learn/teens/teen-creative-agency",
    "Automotive High School Internship Program": "https://www.nyc.gov/site/dcas/index.page",
    "Work Study Student Program": "https://www.loc.gov/about/jobs-and-internships/",
    "Tech Scholars Program": "https://www.nyhistory.org/education/tech-scholars-program",
    "Inspiring Future Scientists through Shadowing (IFSS)": "https://chemistry.stanford.edu/",
    "Teen Art Connect Internship": "https://thecjm.org/",
    "The Young Women's Leadership Institute": "https://barnard.edu/precollege",
    "Summit Program": "https://www.coloradoyoungleaders.org/",
    "Hospital Placement": "https://icahn.mssm.edu/education/high-school-programs",
    "Summer Science Corps": "https://www.delawarenaturesociety.org/",
    "Computer Science for Cyber Security (CS4CS)": "https://www.nyu.edu/",
    "GO Getter Summer Internship": "https://goprojectnyc.org/",
    "Teen Council & Teen Summer": "https://www.bronxmuseum.org/",
    "Biotechnology for Science & Health Academy": "https://scs.georgetown.edu/",
    "Beginner Environmental Leadership Program": "https://www.georgiaaquarium.org/",
    "City Summer Internship": "https://apprenticelearning.org/",
    "Kimberly Querrey Summer Research Program": "https://www.nm.org/",
    "Volunteer Summer Program": "https://www.uclahealth.org/",
    "STEM Enhancement in Earth Science (SEES) Summer High School Intern Program": "https://www.tsgc.utexas.edu/sees-internship/",
    "Garden 2 Market Internship": "https://vancortlandtalliance.org/",
    "National Youth Congress Internship": "https://nationalyouthcongress.org/",
    "Rebel Research Scholars": "https://www.olemiss.edu/",
    "UPWARDS High School Summer Research Training Program": "https://www.mdanderson.org/",
    "College Edge: Summer": "https://www.columbia.edu/",
    "The Field Museum Internship": "https://www.fieldmuseum.org/",
    "Summer Field Biology Internships (FBI)": "https://www.alleypond.org/",
    "Fall Field Biology Internships (FBI)": "https://www.alleypond.org/",
    "Spring Field Biology Internships (FBI)": "https://www.alleypond.org/",
    "Data Science Institute Summer Lab": "https://datascience.uchicago.edu/",
    "Zoo Ambassador": "https://www.zoonewengland.org/",
    "New York Fellows Program": "https://www.ghettofilmschool.org/",
    "View Opportunity": "https://www.inspiritai.com/",
    "Artificial Intelligence Program for High School Students": "https://www.inspiritai.com/",
    "Summer High School Research Internship": "https://www.houstonmethodist.org/",
    "Job Shadow Program": "https://www.les.com/",
    "RISE Teen Program": "https://www.msichicago.org/",
    "Spring Internship Program": "https://www.whitehouse.gov/",
    "The White House Fall Internship Program": "https://www.whitehouse.gov/",
    "The White House Summer Internship Program": "https://www.whitehouse.gov/",
    "High School Interns (Summer)": "https://www.fisheries.noaa.gov/",
    "Thurgood Marshall Summer Law Internship Program": "https://www.nycbar.org/get-legal-help/education-programs/thurgood-marshall-summer-law-internship-program/",
    "Teen Jobs": "https://chicagoparkdistrict.com/",
    "Roswell Park's Summer Cancer Research Experience Program": "https://www.roswellpark.org/",
    "Unity Gardens Internship": "https://www.unitygardens.org/",
    "Green Girls": "https://cityparksfoundation.org/",
    "Page Program": "https://okhouse.gov/",
    "The Apollo Theater Academy High School Internship Program": "https://www.apollotheater.org/education/apollo-theater-academy-internship/",
    "BDL Debate Camp": "https://www.bostondebate.org/",
    "Los Angeles Medical Center Volunteer Program": "https://healthy.kaiserpermanente.org/southern-california/",
    "Fall Internships": "https://castro.house.gov/",
    "Chicago EYES on Cancer Program": "https://www.uchicagomedicine.org/",
    "VALOR JROTC": "https://www.fnal.gov/",
    "Mayor's Office Internship Program": "https://www.nyc.gov/",
    "Lamont-Doherty Earth Observatory Secondary School Field Research Program": "https://www.ldeo.columbia.edu/",
    "Pre-Med Summer Scholar Program": "https://www.uclahealth.org/",
    "Get Inspired Houston (GIH) Internship": "https://sewahouston.org/",
    "High School Summer Internship Program (HS-SIP)": "https://www.training.nih.gov/programs/hs-sip",
    "Seed Crew Greater Boston Region": "https://thefoodproject.org/",
    "Seed Crew North Shore Region": "https://thefoodproject.org/",
    "Malott Family Zoo Intern Program": "https://www.lpzoo.org/",
    "Mikva Summer Fellowship": "https://mikvachallenge.org/",
    "Technology Support - Student Interns": "https://www.flps.k12.mn.us/",
    "LLRISE Workshop": "https://www.ll.mit.edu/outreach/llrise",
    "8-Week Summer Internship for Rising Seniors": "https://baliga.systemsbiology.net/",
    "AMRI High School Summer Research Program": "https://www.uno.edu/",
    "SeA Bilingual STEM Camp": "https://k12.lbl.gov/",
    "Young Scientist Program (YSP) Summer Focus": "https://ysp.wustl.edu/",
    "Riverside Teen Corps Horticulture Internship Program": "https://riversidepark.org/",
    "High School Apprenticeship Program": "https://mjhnyc.org/",
    "Meritocracy Fellowship": "https://www.palantir.com/",
    "KU Medical Center Educational Experience (KEE)": "https://www.kumc.edu/",
    "Research Intern": "https://www.teensinhealth.org/",
    "Adler Planetarium Teen Internship Program": "https://www.adlerplanetarium.org/learn/teens/",
    "History Day": "https://www.nhd.org/",
    "Seasonal Positions & Front Office Openings": "https://www.hartfordyardgoats.com/",
    "STEM Academy at Oak Ridge": "https://www.arc.gov/",
    "District Internship Program": "https://himes.house.gov/",
    "Junior Curators": "https://naturalsciences.org/",
    "High School Student Worker": "https://www.venturacounty.org/",
    "Summer High School Institute": "https://www.uwyo.edu/",
    "Wayne State Discovery to Cure High School Internship Program": "https://mott.wayne.edu/",
    "High School Intern Program": "https://sep.ucsf.edu/",
    "Summer Challenge": "https://www.bu.edu/summer/high-school-programs/",
    "Youth Arts Enterprise": "https://www.afhboston.org/",
    "Summer High School Internship Program": "https://www.nist.gov/iaao/internships",
    "Explorers Teen Program": "https://www.newarkmuseumart.org/",
    "High School Summer Internship Program": "https://my.clevelandclinic.org/",
    "Summer Research Scholar Program": "https://www.hackensackmeridianhealth.org/",
    "Upward Bound Math Science Summer Program": "https://www.uwyo.edu/trcssp/",
    "High School Health Careers Program (HSHCP)": "https://www.umassmed.edu/",
    "Health Sciences Enrichment Institute": "https://www.kumc.edu/",
    "Observers/Job Shadows": "https://www.childrenswi.org/",
    "The AEOP High School Apprenticeship": "https://www.usaeop.com/",
    "Learning at the Bench (LAB) Jumpstart": "https://www.rockefeller.edu/education-and-training/high-school/",
    "Academic Year Weekend": "https://www.columbia.edu/",
    "Academic Year Weekend (Early Deadline)": "https://www.columbia.edu/",
    "College Edge: Academic Year": "https://www.columbia.edu/",
    "HighTech Bound": "https://www.iol.unh.edu/",
    "Congressional Youth Advisory Council (CYAC)": "https://chu.house.gov/",
    "Office of Workforce Development Student Training Program": "https://www.dana-farber.org/",
    "Teen Advisory Board": "https://noguchi.org/",
    "Inspiring Careers in Mental Health": "https://www.utsouthwestern.edu/",
    "Montana Models": "https://www.montana.edu/",
    "Teen Creative Agency Apprenticeship": "https://mcachicago.org/",
    "InterseXtions: Gender & Sexuality": "https://www.brooklynmuseum.org/",
    "Summer Neuroscience Program": "https://www.rockefeller.edu/education-and-training/high-school/",
    "Mining & Explosives Camp": "https://www.sdsmt.edu/",
    "Eighth Judicial District High School Internship Program": "https://www.mycourts.gov/",
    "New York Bioforce": "https://www.engineering.columbia.edu/",
    "Junior Summer Volunteer Program": "https://www.bmc.org/",
    "Henry Mayo Newhall Hospital Volunteer Program": "https://www.henrymayo.com/",
    "Environmental Education Internship": "https://www.savebaysf.org/",
    "Pre-Baccalaureate Program": "https://barnard.edu/precollege",
    "UW Allen School Changemakers in Computing": "https://www.cs.washington.edu/",
    "Mayor's Youth Council": "https://www.boston.gov/",
    "SF YouthWorks & MYEEP": "https://www.jcyc.org/",
    "New Victory Usher Corps": "https://newvictory.org/",
    "Woodland Ecology Research Mentorship (WERM)": "https://wavehill.org/",
    "High School and College Student Internship Program": "https://www.brla.gov/",
    "The Summer Youth Employment Program": "https://projectselfsufficiency.org/",
    "Urban Design and Planning Pre-College Fellowship": "https://the-bac.edu/",
    "Next Generation STEM Internships Program (NGSI)": "https://www.ornl.gov/",
    "Be Your Own Boss Internship": "https://futurefounders.com/",
    "Environmentor Program": "https://www.rise-nyc.org/",
    "Young Adult Leadership Council": "https://artswestchester.org/",
    "Teen Conservation Leaders": "https://www.montereybayaquarium.org/",
    "The Urban Journalism Workshop": "https://www.nyu.edu/",
    "Center for Imaging Science Summer High School Intern Program": "https://www.cis.rit.edu/",
    "Summer Online Pre-College Courses for High School Students": "https://sce.cornell.edu/",
    "Winter Online Pre-College Courses for High School Students": "https://sce.cornell.edu/",
    "Three-Week Session Residential Precollege Studies Program": "https://sce.cornell.edu/",
    "Summer Programming": "https://www.sfusd.edu/",
    "Santa Clarita Valley Historical Society Docent": "https://www.scvhs.org/",
    "Summer Youth Internship Program": "https://www.mos.org/",
    "Ochsner STAR Summer Scholars Program": "https://www.ochsner.org/",
    "Women Empowered Through Business (WEB) Institute": "https://haslam.utk.edu/web/",
    "Pathways Internship Program": "https://careers.state.gov/intern/student-programs/",
    "The Norman Mineta Bay Area Summer Academy": "https://www.mtc.ca.gov/careers/internships",
    "Einstein Montefiore Summer High School Research Program": "https://einsteinmed.edu/",
    "Young Leaders Academy": "https://louisville.edu/",
    "Media Makers": "https://www.cstones.org/",
    "Change Creators": "https://www.cstones.org/",
    "Lancaster Museum of Art and History Volunteer": "https://www.lancastermoah.org/",
    "Odysea Aquarium Internship Program": "https://www.odyseaaquarium.com/",
    "Volunteer Services": "https://www.mymarinhealth.org/",
    "Discovery Program": "https://www.nm.org/",
    "Youth Conservation Corp Crew Member Application": "https://www.lcfpd.org/",
    "Student Historian Internship Program": "https://www.nyhistory.org/",
    "Summer Youth Internship - Charleston County": "https://www.charlestoncounty.org/",
    "Health Careers Summer Internship Program": "https://www.hawaiipacifichealth.org/",
    "Youth Summer Program": "https://www.brighamandwomens.org/",
    "RCPD Internships": "https://www.rcgov.org/",
    "Los Angeles Fellows Program": "https://www.ghettofilmschool.org/",
    "Internships for Credit &/or Experience": "https://www.gloucestercountynj.gov/",
    "Anchorage Fishing Intern": "https://www.alaskageographic.org/",
    "Summer Camp Counselor": "https://www.wvbaptistcamps.org/",
    "Next Gen High School Internship Program": "https://med.emory.edu/",
    "Science Internship Program": "https://my.clevelandclinic.org/",
    "DPA's Law and Justice Reform Internship Program": "https://sfgov.org/",
    "Summer Student Research Program": "https://pediatrics.ucsf.edu/",
    "Academy/DPHA Summer Internship": "https://www.delamed.org/",
    "Academy/DPHA Spring Internship": "https://www.delamed.org/",
    "Academy/DPHA Fall Internship": "https://www.delamed.org/",
    "Student Research Internship": "https://www.scripps.edu/",
    "Baruch College Now STEM Research Academy": "https://www.baruch.cuny.edu/",
    "Coastal Classroom": "https://cityparksfoundation.org/",
    "Veterinary Sciences Placement": "https://icahn.mssm.edu/education/high-school-programs",
    "Discovery Squad": "https://www.cmhouston.org/",
    "Youth Employment Services (YES) Program": "https://www.santa-clarita.com/",
    "Berkeley Lab K-12 - Experiences in Research": "https://k12.lbl.gov/",
    "SAGE Summer Camp Director's Apprenticeship Program": "https://k12.lbl.gov/",
    "GGG Teen Entrepreneur": "https://getgirlsgoing.org/",
    "Teen Intern (Library)": "https://www.santabarbaraca.gov/",
    "Engineering High School Intern": "https://www.lockheedmartin.com/",
    "NASA Fall High School Internship": "https://intern.nasa.gov/",
    "NASA Summer High School Internship": "https://intern.nasa.gov/",
    "YouthBridge-NY Fellowship": "https://youthbridge-ny.org/",
    "High School Learn and Earn Program": "https://ct.gov/",
    "Journey to Leadership Program": "https://www.bali-nyc.org/",
    "Haggerty Scholars Program": "https://www.oregonfba.org/",
    "UB/Experiential Learning in Emerging STEM Technologies": "https://www.buffalo.edu/",
    "High School Program": "https://healthy.kaiserpermanente.org/",
    "Research Internship": "https://basepair.org/",
    "Medical and Scientific Exploration Program (MSEP)": "https://icahn.mssm.edu/education/high-school-programs",
    "UB National Grid Sustainability Camp": "https://www.buffalo.edu/",
    "California State Parks Student Employment Program": "https://www.parks.ca.gov/",
    "Hands on Experience and Internships": "https://www.missouriinnovationcampus.com/",
    "Creative Practice": "https://www.brooklynmuseum.org/education/public_programs/teen_programs",
    "High School Internship (Venture Analyst)": "https://www.1435capital.com/",
    "Empowered Professionals": "https://www.uvu.edu/",
    "Teen Work Study Program": "https://www.sheddaquarium.org/",
    "Youth Action Institute": "https://www.innovatingjustice.org/",
    "STEAM Team": "https://www.mfa.org/",
    "AIMI Summer Research Internship": "https://aimi.stanford.edu/",
    "Student Internship Job": "https://www.aztecsd.org/",
    "PrepareRI High School Internship Program": "https://s4rf.org/",
    "Young Scholars Program (YSP)": "https://www.northeastern.edu/",
    "UChicago Summer Session Pre-College Program": "https://summer.uchicago.edu/",
    "The Summer Bridge Programs": "https://uic.edu/",
    "Artslife": "https://madmuseum.org/",
    "Emerging Filmmaker Program": "https://tallgrassfilm.org/",
    "BAC Summer Academy for High School Students": "https://the-bac.edu/",
    "Research in Science & Engineering (RISE) Internship/Practicum": "https://www.bu.edu/summer/high-school-programs/rise/",
    "Vermont Adaptive's Apprenticeship Program": "https://www.vermontadaptive.org/",
    "The Columbia Climate School in the Green Mountains": "https://www.climate.columbia.edu/",
    "Legacy Youth Leadership Program": "https://www.bcri.org/",
    "American Red Cross Teen Volunteer": "https://www.redcross.org/volunteer/",
    "Next Generation STEM Internship Program": "https://www.ornl.gov/",
    "Raleigh Summer Youth Employment Program (RSYEP)": "https://raleighnc.gov/",
    "NYU Precollege": "https://www.nyu.edu/admissions/high-school-programs.html",
    "NYU Precollege Fall": "https://www.nyu.edu/admissions/high-school-programs.html",
}

wb = openpyxl.load_workbook(SRC)
ws = wb["All Opportunities"]
hdr = [str(c.value).strip() if c.value else "" for c in ws[1]]
name_i = 0
url_i = hdr.index("Link")

added = 0
for row in ws.iter_rows(min_row=2):
    nm = row[name_i].value
    if not nm:
        continue
    key = str(nm).strip()
    if key in URLS and not (row[url_i].value and str(row[url_i].value).strip()):
        row[url_i].value = URLS[key]
        added += 1

wb.save(SRC)
print(f"Linked {added} rows")wb.save(SRC)
print(f"Linked {added} rows")